### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by egonson** [paritytech/ethabi#126]
Build errors on Ubuntu16.10

cargo install ethabi-cli
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading ethabi-cli v5.1.0                                                  
  Installing ethabi-cli v5.1.0                                                  
 Downloading serde_derive v1.0.79
 Downloading error-chain v0.12.0                                                
 Downloading serde v1.0.79                                                      
 Downloading docopt v0.8.3                                                      
 Downloading rustc-hex v1.0.0                                                   
 Downloading ethabi v5.1.2                                                      
 Downloading proc-macro2 v0.4.19                                                
 Downloading syn v0.15.4                                                        
 Downloading quote v0.6.8                                                       
 Downloading unicode-xid v0.1.0                                                 
 Downloading lazy_static v1.1.0                                                 
 Downloading regex v0.2.11                                                      
 Downloading strsim v0.6.0                                                      
 Downloading version_check v0.1.4                                               
 Downloading memchr v2.1.0                                                      
 Downloading thread_local v0.3.6                                                
 Downloading aho-corasick v0.6.8                                                
 Downloading regex-syntax v0.5.6                                                
 Downloading utf8-ranges v1.0.1                                                 
 Downloading libc v0.2.43                                                       
 Downloading cfg-if v0.1.5                                                      
 Downloading ucd-util v0.1.1                                                    
 Downloading rustc-hex v2.0.1                                                   
 Downloading ethereum-types v0.4.0                                              
 Downloading tiny-keccak v1.4.2                                                 
 Downloading serde_json v1.0.27                                                 
 Downloading ethbloom v0.5.0                                                    
 Downloading ethereum-types-serialize v0.2.1                                    
 Downloading uint v0.4.1                                                        
 Downloading crunchy v0.1.6                                                     
 Downloading fixed-hash v0.2.2                                                  
 Downloading heapsize v0.4.2                                                    
 Downloading rand v0.4.3                                                        
 Downloading byteorder v1.2.6                                                   
 Downloading ryu v0.2.6                                                         
 Downloading itoa v0.4.3                                                        
   Compiling proc-macro2 v0.4.19                                                
   Compiling serde v1.0.79
   Compiling ryu v0.2.6
   Compiling crunchy v0.1.6
   Compiling version_check v0.1.4
   Compiling libc v0.2.43
   Compiling unicode-xid v0.1.0
   Compiling utf8-ranges v1.0.1
   Compiling strsim v0.6.0
   Compiling byteorder v1.2.6
   Compiling cfg-if v0.1.5
   Compiling error-chain v0.12.0
   Compiling ucd-util v0.1.1
   Compiling rustc-hex v1.0.0
   Compiling rustc-hex v2.0.1
   Compiling itoa v0.4.3
   Compiling heapsize v0.4.2
   Compiling regex v0.2.11
   Compiling rand v0.4.3
   Compiling lazy_static v1.1.0
   Compiling memchr v2.1.0
   Compiling regex-syntax v0.5.6
   Compiling tiny-keccak v1.4.2
   Compiling quote v0.6.8
   Compiling thread_local v0.3.6
   Compiling fixed-hash v0.2.2
   Compiling uint v0.4.1
   Compiling aho-corasick v0.6.8
error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:343:22
    |
343 | pub fn split_u128(a: u128) -> (u64, u64) {
    |                      ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:176:48
     |
176  |                             let (hi, low) = $crate::split_u128(a as u128 * b as u128);
     |                                                                     ^^^^
...
1377 | construct_uint!(U256, 4);
     | ------------------------- in this macro invocation

error[E0658]: 128-bit type is unstable (see issue #35118)
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:176:60
     |
176  |                             let (hi, low) = $crate::split_u128(a as u128 * b as u128);
     |                                                                                 ^^^^
...
1377 | construct_uint!(U256, 4);
     | ------------------------- in this macro invocation

error[E0658]: 128-bit type is unstable (see issue #35118)
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:176:48
     |
176  |                             let (hi, low) = $crate::split_u128(a as u128 * b as u128);
     |                                                                     ^^^^
...
1378 | construct_uint!(U512, 8);
     | ------------------------- in this macro invocation

error[E0658]: 128-bit type is unstable (see issue #35118)
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:176:60
     |
176  |                             let (hi, low) = $crate::split_u128(a as u128 * b as u128);
     |                                                                                 ^^^^
...
1378 | construct_uint!(U512, 8);
     | ------------------------- in this macro invocation

error[E0658]: 128-bit type is unstable (see issue #35118)
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:176:48
     |
176  |                             let (hi, low) = $crate::split_u128(a as u128 * b as u128);
     |                                                                     ^^^^
...
1386 |         U512(uint_full_mul_reg!(U256, 4, self, other))
     |              ---------------------------------------- in this macro invocation

error[E0658]: 128-bit type is unstable (see issue #35118)
    --> /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/uint-0.4.1/src/uint.rs:176:60
     |
176  |                             let (hi, low) = $crate::split_u128(a as u128 * b as u128);
     |                                                                                 ^^^^
...
1386 |         U512(uint_full_mul_reg!(U256, 4, self, other))
     |              ---------------------------------------- in this macro invocation

   Compiling syn v0.15.4
   Compiling ethereum-types-serialize v0.2.1
   Compiling serde_json v1.0.27
error: aborting due to 7 previous errors

error: Could not compile `uint`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ethabi-cli v5.1.0`, intermediate artifacts can be found at `/tmp/cargo-install.QTTMvBtqPHyL`

Caused by:
  build failed

**Comment by dvdplm** [comment]
@egonson That looks like an outdated version of Rust. What is the output of running `rustc -V` on your system?

The `U128` type was stabilized in version 1.26 I think. Can you try with a more recent version of Rust?

**Comment by egonson** [comment]
After upgrading rustc to 1.30.0-nightly, it works.
Thank you very much for rapid response.
